function Sindy_ODEs = Sindy_ODE_RHS(t,in2,in3)
%Sindy_ODE_RHS
%    Sindy_ODEs = Sindy_ODE_RHS(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    03-Dec-2024 21:41:36

z1 = in2(1,:);
z2 = in2(2,:);
z3 = in2(3,:);
z4 = in2(4,:);
t2 = z1.*2.0;
t3 = z2.*-1.0;
t5 = z2.*-2.0;
t7 = z3.^2;
t8 = z4.^2;
t9 = t3+z1;
t12 = t2+t5;
t10 = cos(t9);
t11 = sin(t9);
t13 = sin(t12);
t14 = t10.^2;
t15 = t14-1.300000000000011;
t16 = 1.0./t15;
Sindy_ODEs = [z3;z4;t16.*(sin(t5+z1).*4.265217391304304+sin(z1).*6.824347826086978+t8.*t11.*8.695652173912976e-1+t7.*t13.*5.0e-1);t16.*(sin(t2+t3).*6.376499999999965-sin(z2).*6.376499999998487+t7.*t11.*1.495000000000005+t8.*t13.*5.0e-1).*-1.0];
end
